version: '3'
services:
  db:
    image: mariadb:10.4.8
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: Kobaias1?1701?
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    restart: always
volumes:
  db_data: